[package]
name = "iron_pi"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
colored = "2.1.0"
criterion = { version = "0.5.1", features = ["real_blackbox", "html_reports"] }
rug = { version = "1.24.1", features = ["serde"] }

[profile.profile]
inherits = "release"
debug = true

[[bench]]
name = "bench"
harness = false
